spring:
  profiles:
    active: default
  application:
    name: BackEndApiPlantas
  datasource:
    url: jdbc:mysql://localhost:3306/plantasdb
    username: root
    password: ""
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    time-zone: UTC
  mvc:
    dispatch-options-request: true

jwt:
  secret: "bXlTdXBlclNlY3JldEtleTEyMzQ1Njc4OTBBQkNERUY="
  expiration: 86400000

security:
  password:
    strength: 12